<<<<<<< HEAD
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

before_script:
  - composer install --dev --no-progress
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'create database ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"

script: phpunit --coverage-text --configuration tests/travis/$DB.phpunit.xml

branches:
  only:
    - develop
    - /^feature\/.+$/
=======
branches:
  except:
    - 2.1-stable
    - master
>>>>>>> db4f429fdbc3e3cdca53f5d9ab1daf5811c5ac19
